# Generated by Django 3.2.8 on 2021-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSys', '0002_remove_pacientes_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='Numero',
            field=models.IntegerField(default=0),
        ),
    ]
