# Generated by Django 3.2.8 on 2021-10-09 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSys', '0003_pacientes_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='Cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Pais',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='UF',
            new_name='uf',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='data',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 10, 9, 18, 18, 5, 556237, tzinfo=utc)),
        ),
    ]
