# Generated by Django 3.2.8 on 2021-10-09 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSys', '0004_auto_20211009_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='data',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 10, 9, 15, 35, 4, 649249)),
        ),
    ]
