# Generated by Django 3.2.8 on 2021-10-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSys', '0006_auto_20211009_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=60)),
                ('data', models.DateTimeField(verbose_name='10/10/21')),
            ],
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='data',
            field=models.DateTimeField(verbose_name='10/10/21'),
        ),
    ]
