# Generated by Django 3.2.8 on 2021-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalSys', '0010_alter_pacientes_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
